# Generated by Django 4.1.5 on 2023-01-19 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('timeslot', models.DateTimeField()),
                ('description', models.TextField()),
                ('thumbnail', models.ImageField(upload_to='media')),
                ('slug', models.CharField(max_length=50)),
            ],
        ),
    ]
