# Generated by Django 4.1.5 on 2023-02-06 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_event_serial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsorship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=200)),
                ('company_name', models.CharField(max_length=200)),
                ('contact_person', models.CharField(max_length=200)),
                ('designation', models.CharField(max_length=200)),
                ('mail', models.EmailField(max_length=200)),
                ('sponsorship_type', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='event',
            name='serial',
        ),
    ]
